### PR TITLE
WIP trying to get info from the test bubble

### PR DESCRIPTION
**Pull request by kelfink**

### CODE REVIEW

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by RamuKammagani-osi** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Pull request closed without merging**
