### PR TITLE
COG 1110 detail view changelog api

### PR DESCRIPTION
**Pull request by kelfink**
#### Which User story does this relate to (link)?
- https://osi-cwds.atlassian.net/browse/COG-1110

#### Brief feature description
- Adds real (Elastic Search-based) API data to the ChangeLog component

### CODE REVIEW

**Comment by kelfink** [comment]
retest this please

**Comment by Nasir2712** [comment]
My assumption is we should review this PR after merging @Sushmareddy-OSI PR just because this might get a bunch of merge conflicts which could potentially break some functionality.

**Comment by Nasir2712** [comment]
Also, any specific reason to add minor label rather than patch?

**Comment by kelfink** [comment]
> Also, any specific reason to add minor label rather than patch?

Doesn't a patch imply it's just fixing a bug and doesn't change compatibility?  This change depends on the functionality added to Perry which supplies the changelog data.

**Pull request closed without merging**
