### PR TITLE
COG-1468 audit events Made By value is shown empty in case of null value

### PR DESCRIPTION
**Pull request by sorych**
#### Which User story does this relate to (link)?
- COG-1468

#### Brief feature description
- Audit events Made By value is shown empty in case of null value

### CODE REVIEW

**Comment by sorych** [comment]
> Can you please add a test case for this

@RamuKammagani-osi tests have been added

**Comment by sorych** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Pull request merged**
