### PR TITLE
Cog 1370 display fuzzy search results

### PR DESCRIPTION
**Pull request by Sushmareddy-OSI**
#### Which User story does this relate to (link)?
[COG-1370](https://osi-cwds.atlassian.net/browse/COG-1370)

#### Brief feature description
-Display Exact and Fuzzy search results

### CODE REVIEW

**Comment by Sushmareddy-OSI** [comment]
retest this please

**Comment by Sushmareddy-OSI** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Comment by mgrmax** [comment]
retest this please

**Pull request merged**
