### PR TITLE
CMO-447 :fixing Acceptance Test cases.

### PR DESCRIPTION
**Pull request by JGovindaraj**
CMO-447 -  Verify CD Pipeline component 'cap' for CARES automated smoketest
-

Fixing test cases.
-

### CODE REVIEW

**Comment by JGovindaraj** [comment]
retest this please

**Comment by JGovindaraj** [comment]
ok to test

**Comment by SashaKyz** [comment]
CodeClimate check

**Comment by JGovindaraj** [comment]
Can one of the admins verify this patch?

**Comment by JGovindaraj** [comment]
add to whitelist

**Pull request merged**
