### PR TITLE
COG-284 Tabbing exposes phantom button

### PR DESCRIPTION
**Pull request by RamuKammagani-osi**
- [x]  Refactor Card component

- [x] Add test cases 

- [x]  Update Verify/Add/User detail cards

### CODE REVIEW

**Comment by RamuKammagani-osi** [comment]
retest this please

**Comment by RamuKammagani-osi** [comment]
retest this please

**Comment by RamuKammagani-osi** [comment]
screen shot 2018-09-18 at 1 57 00 pm
In this If two conditions satisfy it returns two buttons even if we need one, So  i just added a extra condition to return just one, we can pass props to card component whether we need one or two buttons.

**Comment by RamuKammagani-osi** [comment]
@kelfink Sure, I'll see you at your desk then

**Comment by kelfink** [comment]
should we remove this branch?

**Pull request merged**
