### PR TITLE
COG-363 Switch default sorting to use 'for_sort'

### PR DESCRIPTION
**Pull request by kelfink**
Not ready to deploy until integration has the new index mappings.  They are available in pre-int, for now.  

Try:   
`{"query":{"match_phrase_prefix":{"last_name":"M"}},"from":0,"size":50,"sort":[ {"last_name.for_sort": "desc"}]}`
		
or `{"query":{"match_all":{}},"from":0,"size":50,"sort":[ {"last_name.for_sort": "asc"}]}`

### CODE REVIEW

**Comment by RamuKammagani-osi** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Comment by kelfink** [comment]
retest this please

**Pull request merged**
